name: Maintain README
on:
  push:
    branches:
      - main

env:
  DENO_DIR: ./cache

jobs:
  list-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Cache Deno dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('deno.lock') }}

      - run: deno task maintain-readme

      - uses: EndBug/add-and-commit@v7
        with:
          add: README.md
          message: Update README.md
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
